In [8]:
import torch

def check_pytorch_setup():
    print("PyTorch Version:", torch.__version__)
    print("CUDA Available:", torch.cuda.is_available())  # Should be False since you're using CPU

if __name__ == "__main__":
    check_pytorch_setup()


PyTorch Version: 2.2.2+cpu
CUDA Available: False


In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


In [10]:
import torch

# Create a tensor x and set requires_grad=True to track computation with it
x = torch.tensor([2.0], requires_grad=True)

# Define y as a function of x
y = x**2

# Define z as a function of y
z = 3*y + y**2

# Compute the gradient of z with respect to x
z.backward()

# Print the gradient stored in x.grad
print(x.grad)  # Output of the derivative of z with respect to x

tensor([44.])


In [16]:
x = torch.empty(size = (3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
x = torch.rand((3,3))
x

tensor([[0.3829, 0.3017, 0.9117],
        [0.5414, 0.5918, 0.9392],
        [0.2415, 0.1977, 0.4278]])

In [21]:
x = torch.rand((3,3,3))
x

tensor([[[0.8077, 0.9106, 0.0947],
         [0.9561, 0.3762, 0.4613],
         [0.0040, 0.6763, 0.3957]],

        [[0.7247, 0.3872, 0.5277],
         [0.3703, 0.1101, 0.2996],
         [0.1699, 0.2117, 0.9948]],

        [[0.0467, 0.8322, 0.2163],
         [0.1556, 0.1267, 0.3296],
         [0.7426, 0.5055, 0.5664]]])

In [24]:
x = torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

In [26]:
x=torch.linspace(start=0,end=1,steps=11)
x

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

In [29]:
x=torch.empty(size=(1,5)).normal_(mean=0,std=1)
x

tensor([[ 0.5799,  0.0286, -2.1089, -2.2219, -0.7023]])

In [33]:
x=torch.empty(size=(1,5)).uniform_(0,1)
x

tensor([[0.8483, 0.2303, 0.0464, 0.5254, 0.8847]])

In [34]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [35]:
print(x.bool())

tensor([False,  True,  True,  True])


In [36]:
print(x.short()) #int16

tensor([0, 1, 2, 3], dtype=torch.int16)


In [42]:
x_l = x.long() #int64
print(x_l, x_l.dtype)

tensor([0, 1, 2, 3]) torch.int64


In [43]:
x.half() #float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [46]:
x.float(), x.float().dtype #float32

(tensor([0., 1., 2., 3.]), torch.float32)

In [47]:
x.double() #float64

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [49]:
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
z= torch.true_divide(x,y) #term by term division
z

tensor([0.1111, 0.2500, 0.4286])

In [54]:
x

tensor([1, 2, 3])

In [51]:
x**2

tensor([1, 4, 9])

In [55]:
x>2, x>=2

(tensor([False, False,  True]), tensor([False,  True,  True]))

In [56]:
x1 , x2 = torch.rand((2,5)), torch.rand((5,3))
x3 = torch.mm(x1, x2) # = x1.x2, matrix product
x3

tensor([[1.7766, 1.3279, 1.4336],
        [1.0728, 0.5818, 1.0637]])

In [61]:
mat = torch.rand(5, 5)
mat.matrix_power(3)

tensor([[5.7276, 3.6080, 3.6499, 5.3096, 1.9976],
        [3.2242, 2.1280, 1.9432, 3.0038, 1.0967],
        [6.1806, 3.9506, 3.8382, 5.7472, 2.0861],
        [4.6220, 3.0353, 2.9155, 4.2691, 1.6904],
        [3.7215, 2.7252, 2.3436, 3.4465, 1.5580]])

In [60]:
torch.dot(x,y)

tensor(46)

In [64]:
batch = 32
n=10
m=20
p=30

t1 = torch.rand(batch, n, m)
t2 = torch.rand(batch, m, p)
out_bnn = torch.bmm(t1,t2)
out_bnn.shape

torch.Size([32, 10, 30])

In [66]:
matrix = torch.full((5, 5), 10)
vector = torch.arange(5)
vector

tensor([0, 1, 2, 3, 4])

In [68]:
matrix - vector

tensor([[10,  9,  8,  7,  6],
        [10,  9,  8,  7,  6],
        [10,  9,  8,  7,  6],
        [10,  9,  8,  7,  6],
        [10,  9,  8,  7,  6]])

In [69]:
matrix**vector

tensor([[    1,    10,   100,  1000, 10000],
        [    1,    10,   100,  1000, 10000],
        [    1,    10,   100,  1000, 10000],
        [    1,    10,   100,  1000, 10000],
        [    1,    10,   100,  1000, 10000]])